name    'jhoblitt-ganglia'
version '1.0.2'

author 'Joshua Hoblitt <jhoblitt@cpan.org>'
license 'Apache'
project_page 'https://github.com/jhoblitt/puppet-ganglia'
source 'https://github.com/jhoblitt/puppet-ganglia.git'
summary 'Install and configure the ganglia gmond & gmetad daemons + web front end'
description 'Install and configure the ganglia gmond & gmetad daemons + web front end'
dependency 'puppetlabs/stdlib', '>= 3.0.0'
