name    'jhoblitt-ganglia'
version '0.0.1'

author 'Joshua Hoblitt <jhoblitt@cpan.org>'
license 'GNU General Public License 2 or any later version'
project_page 'https://github.com/jhoblitt/puppet-ganglia'
source 'https://github.com/jhoblitt/puppet-ganglia.git'
summary 'install and configure the ganglia gmond & gmetad daemons + web front end'
description 'install and configure the ganglia gmond & gmetad daemons + web front end'
dependency 'puppetlabs/stdlib', '>= 1.0.0'
